some improvements

diff --git a/CometVisuBase/cometvisu-entrypoint b/CometVisuBase/cometvisu-entrypoint
--- a/CometVisuBase/cometvisu-entrypoint
+++ b/CometVisuBase/cometvisu-entrypoint
@@ -19,18 +19,17 @@ fi
 
 case "${BACKEND_NAME}" in
     *knxd*)
-        if [ x"${KNX_INTERFACE}" != x"" ]; then
-            echo "starting knxd"
-            knxd -i $KNX_INTERFACE -e $KNX_PA $KNXD_PARAMETERS
-            sleep 0.2
-            chmod a+w /run/knx
-            echo "if ! pidof knxd >/dev/null; then echo 'Error: knxd not running'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
-            echo "if [ ! -e /run/knx ]; then echo 'Error: knxd socket does not exist'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
-            echo "if [ ! -S /run/knx ]; then echo 'Error: /run/knx is not a socket'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
-            echo "if [ \`ls -l /run/knx | cut -c 2-10\` != \"rwxrwxrwx\" ]; then echo 'Error: /run/knx permissions are wrong:'; ls -l /run/knx; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
+        if [ "${KNXD_PARAMETERS}" != "" ]; then
+            echo "creating knxd config file completely based on values from KNXD_PARAMETERS (${KNXD_PARAMETERS})"
         else
-            echo "ERROR: knxd backend selected, but KNX_INTERFACE is not set!"
+            KNXD_PARAMETERS="-i ${KNX_INTERFACE} -e ${KNX_PA} -E ${KNX_CLIENT_PAS} -u -d/var/log/eibd.log -c"
+            echo "creating knxd config file from single parameters (${KNXD_PARAMETERS})"
         fi
+        /usr/lib/knxd_args ${KNXD_PARAMETERS} > /etc/knxd.conf
+        echo -n "starting knxd - version: " && knxd --version
+        knxd /etc/knxd.conf
+        echo "if ! pidof knxd >/dev/null; then echo 'Error: knxd not running'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
+        echo "if [ ! -e /run/knx ]; then echo 'Error: knxd socket does not exist'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
         ;;
 esac
 
