Fix order of knxd arguments

diff --git a/CometVisuBase/cometvisu-entrypoint b/CometVisuBase/cometvisu-entrypoint
--- a/CometVisuBase/cometvisu-entrypoint
+++ b/CometVisuBase/cometvisu-entrypoint
@@ -12,7 +12,7 @@ fi
 if [ "${KNXD_PARAMETERS}" != "" ]; then
     echo "creating knxd config file completely based on values from KNXD_PARAMETERS (${KNXD_PARAMETERS})"
 else
-    KNXD_PARAMETERS="-c -d/dev/stdout -u ${KNX_INTERFACE} -e ${KNX_PA} -E ${KNX_CLIENT_PAS}"
+    KNXD_PARAMETERS="-c -d/dev/stdout -u /run/knx -e ${KNX_PA} -E ${KNX_CLIENT_PAS} ${KNX_INTERFACE}"
     echo "creating knxd config file from single parameters (${KNXD_PARAMETERS})"
 fi
 knxd_args ${KNXD_PARAMETERS} > /etc/knxd.conf
@@ -20,7 +20,7 @@ echo -n "starting knxd - version: " && knxd --version
 knxd /etc/knxd.conf
 chmod a+w /run/knx
 echo "if ! pidof knxd >/dev/null; then echo 'Error: knxd not running'; \$badhealth; exit 1; fi" >> /usr/local/bin/healthcheck
-echo "if [ ! -e /run/knx ]; then echo 'Error: knxd socked does not exist'; \$badhealth; exit 1; fi" >> /usr/local/bin/healthcheck
+echo "if [ ! -e /run/knx ]; then echo 'Error: knxd socket does not exist'; \$badhealth; exit 1; fi" >> /usr/local/bin/healthcheck
 
 CGI_URL_PATH=${CGI_URL_PATH:-/cgi-bin/}
 if [ "${CGI_URL_PATH:-/cgi-bin/}" != "/cgi-bin/" ]; then
