fail when /run/knxd does not exist

diff --git a/CometVisuBase/cometvisu-entrypoint b/CometVisuBase/cometvisu-entrypoint
--- a/CometVisuBase/cometvisu-entrypoint
+++ b/CometVisuBase/cometvisu-entrypoint
@@ -21,13 +21,19 @@ if [ "${KNXD_PARAMETERS}" != "" ] || [ "${KNX_INTERFACE}" != "" ]; then
     if [ "${KNXD_PARAMETERS}" != "" ]; then
         echo "creating knxd config file completely based on values from KNXD_PARAMETERS (${KNXD_PARAMETERS})"
     else
-        KNXD_PARAMETERS="-e ${KNX_PA} -E ${KNX_CLIENT_PAS} -u -d/var/log/knxd.log -c -B single -b ${KNX_INTERFACE}"
+        KNXD_PARAMETERS="-e ${KNX_PA} -E ${KNX_CLIENT_PAS} -u -d/var/log/knxd.log -c -B single -A retry-delay=1 -b ${KNX_INTERFACE}"
         echo "creating knxd config file from single parameters (${KNXD_PARAMETERS})"
     fi
     /usr/lib/knxd_args ${KNXD_PARAMETERS} > /etc/knxd.conf
     echo -n "starting knxd - version: " && knxd --version
     knxd /etc/knxd.conf
-    sleep 0.2
+    sleep 5
+    if [ ! -S "/run/knx" ]; then 
+        echo 'Error: knxd socket does not exist'; 
+        ls -la /run;
+        cat /var/log/knxd.log;
+        exit 1; 
+    fi
     chmod a+rwx /run/knx
     echo "if ! pidof knxd >/dev/null; then echo 'Error: knxd not running'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
     echo "if [ ! -e /run/knx ]; then echo 'Error: knxd socket does not exist'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
@@ -78,7 +84,10 @@ if [ x"${BACKEND_PROXY_SOURCE}" != x"" ] && [ x"${BACKEND_PROXY_TARGET}" != x"" 
     a2enconf cv-proxy.conf > /dev/null
 fi
 
-rm /var/log/apache2/access.log
+if [ -f "/var/log/apache2/access.log" ]; then
+    rm /var/log/apache2/access.log
+fi
+
 if [ x"${ACCESS_LOG}" = x"true" ]
     then ln -s /dev/stdout /var/log/apache2/access.log
     else ln -s /dev/null /var/log/apache2/access.log
