Make path to knxd absolute so that it can be found

diff --git a/CometVisuBase/cometvisu-entrypoint b/CometVisuBase/cometvisu-entrypoint
--- a/CometVisuBase/cometvisu-entrypoint
+++ b/CometVisuBase/cometvisu-entrypoint
@@ -37,13 +37,13 @@ if [ "${KNXD_PARAMETERS}" != "" ] || [ "${KNX_INTERFACE}" != "" ]; then
 
     if [ x"${NO_ENTRYPOINT_KNXD}" = x"false" ]; then
         echo -n "starting knxd - version: " && knxd --version
-        knxd /etc/knxd.ini
+        /usr/bin/knxd /etc/knxd.ini
         sleep 5
-        if [ ! -S "/run/knx" ]; then 
-            echo 'Error: knxd socket does not exist'; 
+        if [ ! -S "/run/knx" ]; then
+            echo 'Error: knxd socket does not exist';
             ls -la /run;
             cat /var/log/knxd.log;
-            exit 1; 
+            exit 1;
         fi
         chmod a+rwx /run/knx
         echo "if ! pidof knxd >/dev/null; then echo 'Error: knxd not running'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
