add default interface options, add option to disable apache starting in foreground (used by distrobox based on this container)

diff --git a/CometVisuBase/cometvisu-entrypoint b/CometVisuBase/cometvisu-entrypoint
--- a/CometVisuBase/cometvisu-entrypoint
+++ b/CometVisuBase/cometvisu-entrypoint
@@ -21,7 +21,7 @@ if [ "${KNXD_PARAMETERS}" != "" ] || [ "${KNX_INTERFACE}" != "" ]; then
     if [ "${KNXD_PARAMETERS}" != "" ]; then
         echo "creating knxd config file completely based on values from KNXD_PARAMETERS (${KNXD_PARAMETERS})"
     else
-        KNXD_PARAMETERS="-e ${KNX_PA} -E ${KNX_CLIENT_PAS} -u -d/var/log/knxd.log -c -B single -A retry-delay=1 -b ${KNX_INTERFACE}"
+        KNXD_PARAMETERS="-e ${KNX_PA} -E ${KNX_CLIENT_PAS} -u -d/var/log/knxd.log -c ${KNX_INTERFACE_OPTIONS} -b ${KNX_INTERFACE}"
         echo "creating knxd config file from single parameters (${KNXD_PARAMETERS})"
     fi
     /usr/lib/knxd_args ${KNXD_PARAMETERS} > /etc/knxd.conf
@@ -44,6 +44,7 @@ CGI_URL_PATH=${CGI_URL_PATH:-/cgi-bin/}
 BACKEND_KNXD=${BACKEND_KNXD:-${CGI_URL_PATH}l}
 BACKEND_OPENHAB=${BACKEND_OPENHAB:-$CGI_URL_PATH}
 BASE_URL=${BACKEND_KNXD%?}
+NO_ENTRYPOINT_APACHE=${NO_ENTRYPOINT_APACHE:-false}
 
 echo "Server side configuration parameters:"
 echo "BACKEND_NAME: '${BACKEND_NAME}'"
@@ -84,21 +85,24 @@ if [ x"${BACKEND_PROXY_SOURCE}" != x"" ] && [ x"${BACKEND_PROXY_TARGET}" != x"" 
     a2enconf cv-proxy.conf > /dev/null
 fi
 
-if [ -f "/var/log/apache2/access.log" ]; then
-    rm /var/log/apache2/access.log
-fi
+if [ x"${NO_ENTRYPOINT_APACHE}" = x"false" ]; then   
 
-if [ x"${ACCESS_LOG}" = x"true" ]
-    then ln -s /dev/stdout /var/log/apache2/access.log
-    else ln -s /dev/null /var/log/apache2/access.log
-fi
+    if [ -f "/var/log/apache2/access.log" ]; then
+        rm /var/log/apache2/access.log
+    fi
 
-echo "if ! curl -f -s http://localhost/ >/dev/null; then echo 'Error: apache not responding'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
+    if [ x"${ACCESS_LOG}" = x"true" ]
+        then ln -s /dev/stdout /var/log/apache2/access.log
+        else ln -s /dev/null /var/log/apache2/access.log
+    fi
 
-# first arg is `-f` or `--some-option`
-if [ x"${1#-}" != x"$1" ]; then
-    set -- apache2-foreground "$@"
-fi
+    echo "if ! curl -f -s http://localhost/ >/dev/null; then echo 'Error: apache not responding'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck
 
-echo "running '$@'..."
-exec "$@"
+    # first arg is `-f` or `--some-option`
+    if [ x"${1#-}" != x"$1" ]; then
+        set -- apache2-foreground "$@"
+    fi
+
+    echo "running '$@'..."
+    exec "$@"
+fi;
